[2023-12-16T14:15:29.532+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_json_dag.git_push manual__2023-12-16T09:15:09.134981+00:00 [queued]>
[2023-12-16T14:15:29.539+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_json_dag.git_push manual__2023-12-16T09:15:09.134981+00:00 [queued]>
[2023-12-16T14:15:29.540+0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-16T14:15:29.558+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): git_push> on 2023-12-16 09:15:09.134981+00:00
[2023-12-16T14:15:29.560+0500] {standard_task_runner.py:57} INFO - Started process 23980 to run task
[2023-12-16T14:15:29.563+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_json_dag', 'git_push', 'manual__2023-12-16T09:15:09.134981+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp7etustw6']
[2023-12-16T14:15:29.563+0500] {standard_task_runner.py:85} INFO - Job 42: Subtask git_push
[2023-12-16T14:15:29.602+0500] {task_command.py:416} INFO - Running <TaskInstance: etl_json_dag.git_push manual__2023-12-16T09:15:09.134981+00:00 [running]> on host DESKTOP-32G5QSE.
[2023-12-16T14:15:29.671+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_json_dag' AIRFLOW_CTX_TASK_ID='git_push' AIRFLOW_CTX_EXECUTION_DATE='2023-12-16T09:15:09.134981+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-16T09:15:09.134981+00:00'
[2023-12-16T14:15:29.676+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-16T14:15:29.677+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /home/sourav/airflow && git push']
[2023-12-16T14:15:29.684+0500] {subprocess.py:86} INFO - Output:
[2023-12-16T14:15:29.692+0500] {subprocess.py:93} INFO - fatal: The current branch new has no upstream branch.
[2023-12-16T14:15:29.692+0500] {subprocess.py:93} INFO - To push the current branch and set the remote as upstream, use
[2023-12-16T14:15:29.692+0500] {subprocess.py:93} INFO - 
[2023-12-16T14:15:29.692+0500] {subprocess.py:93} INFO -     git push --set-upstream origin new
[2023-12-16T14:15:29.692+0500] {subprocess.py:93} INFO - 
[2023-12-16T14:15:29.693+0500] {subprocess.py:97} INFO - Command exited with return code 128
[2023-12-16T14:15:29.701+0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/sourav/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 128.
[2023-12-16T14:15:29.704+0500] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_json_dag, task_id=git_push, execution_date=20231216T091509, start_date=20231216T091529, end_date=20231216T091529
[2023-12-16T14:15:29.721+0500] {standard_task_runner.py:104} ERROR - Failed to execute job 42 for task git_push (Bash command failed. The command returned a non-zero exit code 128.; 23980)
[2023-12-16T14:15:29.736+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-16T14:15:29.753+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
