[2023-12-16T15:50:44.203+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_json_dag.dvc_add manual__2023-12-16T10:50:32.545452+00:00 [queued]>
[2023-12-16T15:50:44.210+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_json_dag.dvc_add manual__2023-12-16T10:50:32.545452+00:00 [queued]>
[2023-12-16T15:50:44.210+0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-16T15:50:44.229+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): dvc_add> on 2023-12-16 10:50:32.545452+00:00
[2023-12-16T15:50:44.231+0500] {standard_task_runner.py:57} INFO - Started process 52079 to run task
[2023-12-16T15:50:44.235+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_json_dag', 'dvc_add', 'manual__2023-12-16T10:50:32.545452+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp4ruzjf0_']
[2023-12-16T15:50:44.236+0500] {standard_task_runner.py:85} INFO - Job 91: Subtask dvc_add
[2023-12-16T15:50:44.277+0500] {task_command.py:416} INFO - Running <TaskInstance: etl_json_dag.dvc_add manual__2023-12-16T10:50:32.545452+00:00 [running]> on host DESKTOP-32G5QSE.
[2023-12-16T15:50:44.342+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_json_dag' AIRFLOW_CTX_TASK_ID='dvc_add' AIRFLOW_CTX_EXECUTION_DATE='2023-12-16T10:50:32.545452+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-16T10:50:32.545452+00:00'
[2023-12-16T15:50:44.347+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-16T15:50:44.348+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /home/sourav/airflow && dvc add transformed_data.json']
[2023-12-16T15:50:44.353+0500] {subprocess.py:86} INFO - Output:
[2023-12-16T15:50:45.010+0500] {subprocess.py:93} INFO - ERROR:  output 'transformed_data.json' is already tracked by SCM (e.g. Git).
[2023-12-16T15:50:45.010+0500] {subprocess.py:93} INFO -     You can remove it from Git, then add to DVC.
[2023-12-16T15:50:45.010+0500] {subprocess.py:93} INFO -         To stop tracking from Git:
[2023-12-16T15:50:45.011+0500] {subprocess.py:93} INFO -             git rm -r --cached 'transformed_data.json'
[2023-12-16T15:50:45.011+0500] {subprocess.py:93} INFO -             git commit -m "stop tracking transformed_data.json"
[2023-12-16T15:50:45.197+0500] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-16T15:50:45.204+0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/sourav/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-16T15:50:45.206+0500] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_json_dag, task_id=dvc_add, execution_date=20231216T105032, start_date=20231216T105044, end_date=20231216T105045
[2023-12-16T15:50:45.248+0500] {standard_task_runner.py:104} ERROR - Failed to execute job 91 for task dvc_add (Bash command failed. The command returned a non-zero exit code 1.; 52079)
[2023-12-16T15:50:45.292+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-16T15:50:45.310+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
